name: tiktok_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Updated to a more recent Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0 # Updated to latest stable version
  cupertino_icons: ^1.0.8
  video_player: ^2.7.2 # Updated to latest version
  stacked_services: ^0.9.0 # Updated to latest version
  get_it: ^7.6.4 # Updated to latest version
  cached_network_image: ^3.3.1 # Updated to latest version
  firebase_core: ^2.15.0 # Updated to latest version
  cloud_firestore: ^4.9.2 # Updated to latest version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: TikTokIcons
      fonts:
        - asset: assets/fonts/TikTokIcons.ttf
